### PR TITLE
Remove 3.12 deprecation warning...

### PR DESCRIPTION
**Pull request by rocky**
regarding the use of pkgdata

### CODE REVIEW

**Comment by rocky** [comment]
NB: I will be investigating what's up with building doctest.

**Review by mmatera — APPROVED** [review]
LGTM

**Comment by rocky** [comment]
I looked at the doctest failure. It looks like we have problems with in mathics core and incompatibility with those versions.

Expect some issues or comments raised there.

**Comment by mmatera** [comment]
> I looked at the doctest failure. It looks like we have problems with in mathics core and incompatibility with those versions.
> 
> Expect some issues or comments raised there.

@rocky, I tested the doctests in my laptop against different versions of Python, and they seem to work properly.

**Comment by rocky** [comment]
I was seeing the same kind of failure that is in the failure of the github workflows tracker for mathics-scanner here. 

For example for this: 

```
2015 ( 3): TEST ArcCosh[0.00000000000000000000000000000000000000]
----------------------------------------------------------------------
Test failed: in Reference of Built-in Symbols / Integer and Number-Theoretical Functions / Hyperbolic Functions
Reference of Built-in Symbols
Exception string index out of range

```

Adding a `len()` to the while test addresses this, but we still get the wrong result: 

```
PAGER=cat git diff 
diff --git a/mathics/builtin/makeboxes.py b/mathics/builtin/makeboxes.py
index 58a1b231..d41c64be 100644
--- a/mathics/builtin/makeboxes.py
+++ b/mathics/builtin/makeboxes.py
@@ -108,9 +108,9 @@ def real_to_s_exp(expr, n):
             exp = s.index(".") - 1
             s = s[: exp + 1] + s[exp + 2 :].rstrip("0")
 
-            # consume leading '0's.
+            # Remove leading '0's from the integer part.
             i = 0
-            while s[i] == "0":
+            while i < len(s) and s[i] == "0" :
                 i += 1
                 exp -= 1
             s = s[i:]
```

**Pull request merged**
