### PR TITLE
Named characters optimization

### PR DESCRIPTION
**Pull request by GarkGarcia**
@rocky I'm trying to transfer the installation code to `setup.py`, but I haven't quite figured out how to do so. I'd appreciate if you could give it a try, I'm very confused when it comes to `setuptools`.

### CODE REVIEW

**Comment by GarkGarcia** [comment]
I think I manage to figure it out reading [this post](https://www.anomaly.net.au/blog/running-pre-and-post-install-jobs-for-your-python-packages/):

> You then define a class which inherits from install and override the run method (which is called by Setuptools) to invoke your custom code before or after you call the parent run method install.run(self).

**Comment by rocky** [comment]
> I think I manage to figure it out reading [this post](https://www.anomaly.net.au/blog/running-pre-and-post-install-jobs-for-your-python-packages/):
> 
> > You then define a class which inherits from install and override the run method (which is called by Setuptools) to invoke your custom code before or after you call the parent run method install.run(self).

Cool!  I don't mind helping out. Unfortunately, I've used all the time up I can devote for a couple of days. 

If this isn't working by the time I can next look at it, I will see if I can get going whatever remains.

**Comment by rocky** [comment]
@GarkGarcia it looks like the instructions you are following are too old. 

Here is a simple-minded workaround: don't put this in setup.py. Put the conversion code elsewhere like in admin-tools. 
Then adjust the makefile to run the scripts when the yaml is newer than the JSON files (or the JSON doesn't exist). 

When we make a distribution, we can run `make` to build this and it will make sure that the JSON are around _before_ setup.py runs. 

If nothing else this is probably simpler to debug and get going.

**Comment by GarkGarcia** [comment]
Ok, I think I get what the issue is. Essentially, we need to run the compilation script before `setuptools` does it's thing (so that `characters.json` is copied to the installation folder). However, we don't get to use ANY dependencies before calling `install.run(self)` (i.e. letting `setuptools` do it's thing and quit). This is a problem for us since our installation script requires PyYAML to be around. Also, for some reason there are NO OPTIONS for seting up pre-install scripts (see https://web.archive.org/web/20161202071142/https://bugs.python.org/setuptools/issue41).

We can deal with this issue in three different ways:

1. Replace the YAML file with a JSON/CSV equivalent, so that we can read it with modeles from the Python's stdlib. I really don't like this, because YAML is definitively the best option most ergonomic of the three data-formats, but this the most robust option.
2. Run the script that compiles the JSON at each commit and keep it in the repo. That was we don't need to compile it when running `setup.py` and therefore we don't need PyYAML around.
3. Check if PyYAML is installed in `setup.py` and quit with a descriptive error if it isn't. If PyYAML is installed we simply continue execution and run the compilation script before `setuptools` does it's thing.

For now, I went for the third option. @rocky You can clean it up afterwards if you want to. Personally, I think the second option is the more desirable, but I don't feel like setting-up GitHub Actions at the moment. Again, @rocky please feel free to do so if you feel like it.

**Review by rocky — APPROVED** [review]
This is fine for now.  Improvements can come later and with experience of use.

**Comment by GarkGarcia** [comment]
> This is fine for now. Improvements can come later and with experience of use.

Great. I'll create an issue to track this.

**Comment by rocky** [comment]
> Ok, I think I get what the issue is. Essentially, we need to run the compilation script before `setuptools` does it's thing (so that `characters.json` is copied to the installation folder). However, we don't get to use ANY dependencies before calling `install.run(self)` (i.e. letting `setuptools` do it's thing and quit). This is a problem for us since our installation script requires PyYAML to be around. Also, for some reason there are NO OPTIONS for seting up pre-install scripts (see https://web.archive.org/web/20161202071142/https://bugs.python.org/setuptools/issue41).
> 
> We can deal with this issue in three different ways:
> 
> 1. Replace the YAML file with a JSON/CSV equivalent, so that we can read it with modeles from the Python's stdlib. I really don't like this, because YAML is definitively the best option most ergonomic of the three data-formats, but this the most robust option.

This is what is called a "straw-man" position: something that no one likes, but is put in to make the others more appealing. 

> 2. Run the script that compiles the JSON at each commit and keep it in the repo. That was we don't need to compile it when running `setup.py` and therefore we don't need PyYAML around.

Um, this is why `make` was invented. It builds the JSON when it is needed or needs updating. (Or at least that is the intent).  

> 3. Check if PyYAML is installed in `setup.py` and quit with a descriptive error if it isn't. If PyYAML is installed we simply continue execution and run the compilation script before `setuptools` does it's thing.
> 
> For now, I went for the third option. @rocky You can clean it up afterwards if you want to. Personally, I think the second option is the more desirable, but I don't feel like setting-up GitHub Actions at the moment. Again, @rocky please feel free to do so if you feel like it.

Down the line, I'd like to see the conversion script pulled out of setup.py. Conversion is an intersting thing in of its own right. So I should be able to do the conversion without having to install the Pyhton module. 

But this is small stuff. The most important part was to speed up loading and this I think does that. So THANKS!

**Pull request merged**
